# Site settings
title: Edinburgh Workshop on Neural-Symbolic AI
description: June 5, 2025.      Edinburgh, UK.
# domain: ai-ads.github.io
url: https://ai-ads.github.io
baseurl: /web2024

author:
  name: 'Hang Yu, Yuzhang Yang'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
